repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest revision
    hooks:
      - id: black
        language_version: python3
        args: ['--line-length=120']  # Replace 88 with your desired line length

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version available
    hooks:
      - id: isort
        args: ["--profile", "black"]
